### ISSUE TITLE
thumbnails in picture-group have distorted ratios

### ISSUE THREAD

**Issue by julienmalik** [Psycojoker/prosopopee#18]
in the picture-group sections, thumbnails are distorted.
while this can be ok for landscape picture, portraits suffer from this.

any way to ensure they are always preserved ?

**Comment by julienmalik** [comment]
imho it would be better to crop photos than distort them.

**Comment by julienmalik** [comment]
I believe this is due to #19 actually

**Comment by Psycojoker** [comment]
> I believe this is due to #19 actually

I think so because we use a "keep ratio" function of GM so this shouldn't be a problem (and I've never experienced this bug).
