### ISSUE TITLE
cannot use same image in both a picture-group and cover

### ISSUE THREAD

**Issue by julienmalik** [Psycojoker/prosopopee#19]
this creates two thumbnail for the same picture, but with different size, the second one overwriting the first.
probably thumbnails should have their dimensions in their name.

**Comment by Psycojoker** [comment]
> probably thumbnails should have their dimensions in their name.

This looks like the perfect solution. I'm going to implement this (when I have time ™).

**Comment by julienmalik** [comment]
I have it working. PR is coming in a few days.
