### ISSUE TITLE
LICENSE file

### ISSUE THREAD

**Issue by axitkhurana** [Psycojoker/prosopopee#72]
Thanks for working on this project!

I was wondering if I could use the code here in my personal project. Could you please specify the license (MIT/APL/others etc.) in README or a LICENSE file?

https://help.github.com/articles/licensing-a-repository/

Thanks!

**Comment by beudbeud** [comment]
hi the licence is GPL v3
https://prosopopee.readthedocs.io/en/latest/#licence
