### ISSUE TITLE
invalid date field results in traceback

### ISSUE THREAD

**Issue by jelmer** [Psycojoker/prosopopee#91]
Typoing the date field results in a somewhat confusing error message:

    Traceback (most recent call last):
      File "/home/jelmer/bin/prosopopee", line 10, in <module>
        sys.exit(main())
      File "/home/jelmer/.local/lib/python3.7/site-packages/prosopopee/prosopopee.py", line 629, in main
        galleries=reversed(sorted([x for x in front_page_galleries_cover if x != {}], key=lambda x: x["date"]))
    TypeError: '<' not supported between instances of 'str' and 'datetime.date'

**Comment by Psycojoker** [comment]
Can you provide an example on how to get this error please :)? That would help a lot.

**Comment by jelmer** [comment]
% cat gallery/settings.yaml 
title: California
date: 2013-07-07 12:12
cover: IMG_20130707_095007_1.jpg
light_mode: true

**Comment by beudbeud** [comment]
only the date, not the hour is supported

**Comment by jelmer** [comment]
Yup, I understand that - but the error message could be clearer.
