### ISSUE TITLE
alignment issue when pictures do not fill the line in pictures-group section

### ISSUE THREAD

**Issue by QSchulz** [Psycojoker/prosopopee#92]
When pictures are too small to fill a pictures-group's line (which can happen with two portrait pictures; for example on a 1080p screen since the pictures are x600 thumbnails, only two portrait pictures in one line would make the content of the line ~1200px instead of the ~1920px (it's actually with the current syle.css 77% of that => ~1500px) of available space.

![Alignment issue](https://user-images.githubusercontent.com/4410071/57198936-445a3800-6f79-11e9-9eb9-ec875c9ad687.png)

The issue is particularly present when zooming out:
![Alignment issue zooming out](https://user-images.githubusercontent.com/4410071/57198949-71a6e600-6f79-11e9-8b19-80a6ca3eab26.png)

I'd expect the pictures to fill the whole line.

**Comment by beudbeud** [comment]
Use new branch #95
