### ISSUE TITLE
picture captions?

### ISSUE THREAD

**Issue by paulperry** [Psycojoker/prosopopee#94]
Is there a way to add captions to pictures?
Or to view the photo groups as a photo carousel?

**Comment by Psycojoker** [comment]
Yes for captions https://prosopopee.readthedocs.io/en/latest/sections.html?highlight=caption#images-caption

I don't remember we ever implemented a carousel and I don't see anyone here :/ https://github.com/Psycojoker/prosopopee/tree/master/prosopopee/themes/exposure/templates

**Comment by paulperry** [comment]
I don't see a way to add captions to images in `pictures-group`. If I add the `text` field then I always get a: `Abort: There are something wrong in ./images/settings.yaml line 130`

**Comment by paulperry** [comment]
Now I see that if there is a caption in a `pictures-group` then the image needs to be preceded by  `- name:` .  If there is no caption then the name has to be removed. 

Interestingly, captions show on the top in a serif italicized font, but san-serif at the bottom when in a pictures-group.
