### ISSUE TITLE
Themes folder has to exist or prosopopee crashes

### ISSUE THREAD

**Issue by morremeyer** [Psycojoker/prosopopee#96]
If the themes folder does not exist, the build process instantly crashes.

```
Traceback (most recent call last):
  File "/usr/local/bin/prosopopee", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/prosopopee/prosopopee.py", line 610, in main
    templates = get_gallery_templates(theme)
  File "/usr/local/lib/python3.7/site-packages/prosopopee/prosopopee.py", line 336, in get_gallery_templates
    available_themes = theme, "', '".join(Path(__file__).parent.joinpath("themes").listdir())
  File "/usr/local/lib/python3.7/site-packages/path/__init__.py", line 497, in listdir
    self / child for child in os.listdir(self)
NotADirectoryError: [Errno 20] Not a directory: Path('/usr/local/lib/python3.7/site-packages/prosopopee/themes')
``` 

Affected version: `0.8.2`

I’ll fix this myself as soon as I find the time to do so.

**Comment by KjellConnelly** [comment]
This is happening to me too. Going to `mkdir` and see what happens.

Update: I did, and it needs the themes. Not sure why it's not downloading themes. Going to try to reinstall via `pip` again. If doesn't work, I'll just download repo and move directory

**Comment by jlntrt** [comment]
Any news here? I have the same issue with Python 3.6.9 and the same prosopopee version.

**Comment by Bouni** [comment]
Same issue here, just installed via pip (python 3.8, prosopopee 0.8.2).
The themes dir isn't where it should be (site-packages/prosopopee/themes).
cloning the repo and copy the themes dir to site-packages/prosopopee/themes fixed the issue for me.

**Comment by JocelynDelalande** [comment]
I can confirm it fails. The package seems not no include the themes folder.

Current workarounds I found working : install prosopopee **0.8.1** instead of 0.8.2.

@beudbeud I suppose this is merely a pip packaging issue.

**Comment by beudbeud** [comment]
I just make a new package, normally the issue is fixed
pip3 install prosopopee==0.8.3

**Comment by JocelynDelalande** [comment]
IMHO, issue can be closed. @mauricemeyer

**Comment by morremeyer** [comment]
I didn’t test it myself but it looks pretty fixed to me :)
