### ISSUE TITLE
Paragraph image errors

### ISSUE THREAD

**Issue by mattkerrison** [Psycojoker/prosopopee#97]
In the docs you can insert an image like so:

- type: paragraph
  title: the title
  text: Some text, HTML <b>is allowed</b>.
  image: image.jpg
    float: right
    size: 150px

If I do this, and run a build, I get the error:  _Abort: There are something wrong in_

If I remove the float & size settings it works fine, however I want to set the size and position. any ideas? using v0.8.1 in docker for the builds

**Comment by beudbeud** [comment]
Hi @mattkerrison thanks for your report, you have true there are something wrong, the documentation is not good. I just fix it

https://prosopopee.readthedocs.io/en/latest/sections.html#paragraph
